# prj.conf — Zephyr QEMU build for smart shoe
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
